### ISSUE TITLE
The "bottom-notice" parameter is missing from the invoice.

### ISSUE THREAD

**Issue by lnxcz** [dveldhoen/easyinvoice#107]
I noticed that invoices are generated in the cloud. Is there a possibility that this feature has been removed? It was quite crucial for us, so we would like to know how to replicate this functionality.

**Comment by dveldhoen** [comment]
Hi, it should function as it used to. We just moved to a new api. Are you getting above error?

**Comment by dveldhoen** [comment]
Please let us know if anything doesn't work as it should. We will try to fix it ASAP. We will never make the code public though, since this feature is also natively used for our paid app.

**Comment by dveldhoen** [comment]
We found the issue and are patching the bug as we speak. It should be fixed in about 15 minutes max.

**Comment by lnxcz** [comment]
Alright, thanks. 👏
