### ISSUE TITLE
easyinvoice request are failing with "Request entity too large"

### ISSUE THREAD

**Issue by Manish3323** [dveldhoen/easyinvoice#108]
Hi,
We are using free service of the easyinvoice api.. 
is there any recent changes at server validation for payload size?

since morning IST we are getting 413 "Request entity too large" for payload size as small as 296 Kilo bytes.

do let me know if there are any limits as such ?

**Comment by Manish3323** [comment]
Is this the expected error on free trial expiry?

**Comment by Manish3323** [comment]
okay found the issue, 
when i request without custom template, it returns proper data (request payload : 76kb)
& when i request createInvoice with custom template enabled.. it fails saying request entity too large.. (request entity : ~300kb)

my guess is that, there might be some validation which got added recently for request payloads?

**Comment by dveldhoen** [comment]
Hi, thank you for contacting us. We did move to a new api. Could you send me the payload you use so we can reproduce? We'll try to fix that today then. 

You can send it to info@easyinvoice.cloud

**Comment by Manish3323** [comment]
cool. will share a curl request on this email..

**Comment by Manish3323** [comment]
Thanks, i have sent the email.
Also no rush, take your time as needed. 
For now, we have fixed the issue by reducing encoded html file size.

**Comment by dveldhoen** [comment]
Thanks for the extra information. The bug has been fixed, the pipeline should take about 15 minutes to deploy the changes.

**Comment by Manish3323** [comment]
Thanks a lot, its working for us now.

**Comment by dveldhoen** [comment]
Good to hear, and apologies for the inconvenience. It's always easy to forget something in a large migration. This was one of those things. 😇

**Comment by Manish3323** [comment]
no worries. that happens with the best of people. have a great day 🫂

**Comment by dveldhoen** [comment]
Thanks, you too 👍🏼

**Comment by Manish3323** [comment]
oh yes, one more thing i observed is that, since it was failing on my end, i pressumed it might be because of i choose free service of easyinvoice. i tried upgrading it & payment gateway failed for me thrice with different credit & debit cards of different owners as well just to check its not card related issue.

so i think the payment gateway page (FastSpring) of easyinvoice.com does not work with Indian credit/debit cards. one thing i could gather from that is .. the payment mode is set as recurring for easyinvoice & indian banking system does not allow any international recurring payment mode unless they are from big companies like netflix, google play subscription,(put any  global subscription based company),etc... 
[FYI news letter from RBI](https://economictimes.indiatimes.com/industry/banking/finance/banking/recurring-card-payments-to-be-affected-as-new-credit-debit-card-rules-kick-in-from-october-1/articleshow/86552869.cms?from=mdr)
these are my findings, you might want to cross verify & check on this.

**Comment by dveldhoen** [comment]
I understand the confusion, and appreciate the fact that you are willing to pay for our paid subscription. In fact we are actually on the verge of releasing the paid version for this service. Though easyinvoice.com is (regretably) not our domain name or application. We use https://easyinvoice.cloud, which will soon be migrated to https://budgetinvoice.com.

We will release the paid version in about two weeks time, after which we will lower the rate for the free version. We will also include a guide on how to simply acquire an apikey. Our paid solution will include possibilities for creditcard and PayPal, which should probably cover your needs?

**Comment by dveldhoen** [comment]
The package will also probably be renamed from easyinvoice to budgetinvoice to prevent confusion.

**Comment by Manish3323** [comment]
ohh, thanks for the updates & clarifying my understanding on easyinvoice.com & easyinvoice.cloud.
