### ISSUE TITLE
Cannot read properties of undefined (reading 'createInvoice')

### ISSUE THREAD

**Issue by daenamcclintock** [dveldhoen/easyinvoice#109]
Hi,

I am trying to use this package in my NestJS backend with Typescript and the easyinvoice import is logging to _undefined_ and I am getting the error "Cannot read properties of undefined (reading 'createInvoice')."

Any idea why this could be? I've tried uninstalling and reinstalling the package a few different times, but am still having the same issue. I am working with the newest version of easyInvoice: 3.0.23.

Thanks

**Comment by dveldhoen** [comment]
Thanks for your message, we will have a look ASAP and try to fix it. Can you send me a bit of sample code?

**Comment by dveldhoen** [comment]
I just tried to import easyinvoice in a NestJS application, that worked fine for me. Types were recognized. Please provide me with some code so I can reproduce. Also the ts.config would help.
