### ISSUE TITLE
Not Working in React native

### ISSUE THREAD

**Issue by sikky99** [dveldhoen/easyinvoice#11]

**Comment by dveldhoen** [comment]
Hi, thanks for contacting us. Could you provide us with some extra details so we can try and reproduce the issue?

Did you have a look at our React fiddle?

**Comment by sikky99** [comment]
![error](https://user-images.githubusercontent.com/17407154/88629119-7dc21a80-d0cc-11ea-9bfa-7ba438fc8289.png)

**Comment by dveldhoen** [comment]
Thanks we will look into it

**Comment by dveldhoen** [comment]
React native is not supported for now, but we are looking to support it in the future. Closing this issue for now. Thanks for your feedback.

**Comment by dveldhoen** [comment]
Hi, 

Please have a look at this issue:
https://github.com/dveldhoen/easyinvoice/issues/20

Perhaps it will solve your problem with react native for now.

Kind regards and happy coding!
