### ISSUE TITLE
Hide/disable "due-date" without seeing ":"

### ISSUE THREAD

**Issue by cjkooij** [dveldhoen/easyinvoice#113]
Can the use of "due-date" somehow be disabled?

It seems that currently if you don't pass a value, it will still render the key without a date.
<img width="265" alt="image" src="https://github.com/dveldhoen/easyinvoice/assets/72307251/34c6b30c-929e-45c4-b852-a51e788d7799">

If using te translation to replace "Due date" with a space, the ":" remains.
<img width="259" alt="image" src="https://github.com/dveldhoen/easyinvoice/assets/72307251/93647259-a468-41b7-b094-be11fe6c4cac">

Would be great if there is a way to also hide ":" or have "due-date" disabled fully if not passed.

Thanks for the great library!

**Comment by dveldhoen** [comment]
Thanks for the suggestion! We will look into it as soon as possible.

**Comment by divu050704** [comment]
@cjkooij  just add `<p style='color:white'>` to `due-date` translation property 

```json
"translate": {
            "due-date": "<p style='color:white'>"
}
```

**NOTE-** It might break some features, because the code is not sanitized, so be careful, and code may make code vulnerable to XSS.

**Comment by dveldhoen** [comment]
We fixed this in the next release, should be online in about 15 minutes. If you leave either date, number or dueDate empty the colon should also be hidden.
