### ISSUE TITLE
Cannot read properties of undefined (reading 'createInvoice')

### ISSUE THREAD

**Issue by vladimirantos** [dveldhoen/easyinvoice#115]
I'm trying to call createInvoice as well as in the documentation:
`
import easyinvoice from 'easyinvoice';
await easyinvoice.createInvoice(this._invoiceData);
`

but easyinvoice is undefined. How to import easyinvoice to call createInvoice? 
Thanks

**Comment by dveldhoen** [comment]
Can you create a sample public repo which reproduces the issue? Thank you!

**Comment by vladimirantos** [comment]
Here is the simple example, only installed easyinvoice and try to call createInvoice.

[https://stackblitz.com/edit/nestjs-typescript-starter-baqnvv?file=src%2Fapp.controller.ts](url)

**Comment by sagarnanera** [comment]
Import the module as follows: 

```
import * as easyinvoice from 'easyinvoice';
```

It will work fine, as it will import the whole module and store it in the 'easyinvoice' variable.

Also this will lead to type error in the 'createInvoice' function, to avoid it you can add type as 'any' for the invoice variable.
Here is the updated 'createInvoice' function :

```
private async createInvoice(): Promise<void> {
    const invoice: any = easyinvoice;
    console.log(invoice);
    await invoice.createInvoice({});
  }
  ```

**Comment by vladimirantos** [comment]
It works, thank you

**Comment by dveldhoen** [comment]
@sagarnanera thanks for the help!

**Comment by dveldhoen** [comment]
@vladimirantos I looked at your code, but I think the easier solution is:
import easyinvoice from 'easyinvoice';
await easyinvoice.createInvoice({});

Or did that not work?

**Comment by vladimirantos** [comment]
> @vladimirantos I looked at your code, but I think the easier solution is: import easyinvoice from 'easyinvoice'; await easyinvoice.createInvoice({});
> 
> Or did that not work?

that was my previous version and it didn't work.

**Comment by dveldhoen** [comment]
Alright, thanks for letting me know. We are currently working on a Typescript rewrite. That should be easier to implement.
