### ISSUE TITLE
server couldn't be reached

### ISSUE THREAD

**Issue by lnxcz** [dveldhoen/easyinvoice#116]
from today we couldn't create new invoices. api v2 and v3 seems to be down.

**Comment by dveldhoen** [comment]
Hi, yes apologies we are having some technical issues and have to perform
Emergency maintenance. Should be fixed soon.

**Comment by lnxcz** [comment]
thanks for the clarification 🙏

**Comment by dveldhoen** [comment]
We estimate about 30 minutes, apologies for the inconvenience.

**Comment by Yoofi-A-Appiah** [comment]
Its been more than 30 minutes. Will it be fixed soon please?

**Comment by dveldhoen** [comment]
It has already been fixed a couple of hours ago now. So I'm closing this ticket.
