### ISSUE TITLE
Rate limited

### ISSUE THREAD

**Issue by cjkooij** [dveldhoen/easyinvoice#118]
Unfortunately I've noticed in our response that we have been rate limited, now our production app is not functioning as it should

Is it possible to post the rate limits somewhere and include it in the request so we can keep it in mind?

If it would be possible to lift our rate limit for the next 48 hours so we can seek and implement an alternative, that would be highly appreciated! 

Thank you kindly!

**Comment by dveldhoen** [comment]
Hi,

Sorry to hear that. We could sign you up for the paid version. This will remove the rate limits. Cost is 17,99 euro or dollar a month. We haven't released it to the public (yet).

If you are interested please send us an email at info@easyinvoice.cloud and we will provide with the details.

Best regards
