### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by VinothGox** [dveldhoen/easyinvoice#119]
For the last two days, we couldn't create new invoices. we got Internal server error.
package Version: 3.0.23
Error: { statusCode: 500, message: 'Internal server error' }

**Comment by dveldhoen** [comment]
Thanks for letting us know. Can you give me a config so I can reproduce? Thanks in advance!

**Comment by VinothGox** [comment]
Hi,

This code I use to create invoices. But I can't create it. got an Internal
server error. Package Version: 3.0.24

var easyinvoice = require('easyinvoice');

var data = {

    "customize": {
        //  "template": fs.readFileSync('template.html', 'base64') // Must
be base64 encoded html
    },
    "images": {
        // The logo on top of your invoice
        "logo": "https://public.easyinvoice.cloud/img/logo_en_original.png",
        // The invoice background
        "background": "
https://public.easyinvoice.cloud/img/watermark-draft.jpg"
    },
    // Your own data
    "sender": {
        "company": "Sample Corp",
        "address": "Sample Street 123",
        "zip": "1234 AB",
        "city": "Sampletown",
        "country": "Samplecountry"
        //"custom1": "custom value 1",
        //"custom2": "custom value 2",
        //"custom3": "custom value 3"
    },
    // Your recipient
    "client": {
        "company": "Client Corp",
        "address": "Clientstreet 456",
        "zip": "4567 CD",
        "city": "Clientcity",
        "country": "Clientcountry"
        // "custom1": "custom value 1",
        // "custom2": "custom value 2",
        // "custom3": "custom value 3"
    },
    "information": {
        // Invoice number
        "number": "2021.0001",
        // Invoice data
        "date": "12-12-2021",
        // Invoice due date
        "due-date": "31-12-2021"
    },
    // The products you would like to see on your invoice
    // Total values are being calculated automatically
    "products": [
        {
            "quantity": 2,
            "description": "Product 1",
            "tax-rate": 6,
            "price": 33.87
        },
        {
            "quantity": 4.1,
            "description": "Product 2",
            "tax-rate": 6,
            "price": 12.34
        },
        {
            "quantity": 4.5678,
            "description": "Product 3",
            "tax-rate": 21,
            "price": 6324.453456
        }
    ],
    // The message you would like to display on the bottom of your invoice
    "bottom-notice": "Kindly pay your invoice within 15 days.",
    // Settings to customize your invoice
    "settings": {
        "currency": "USD", // See documentation 'Locales and Currency' for
more info. Leave empty for no currency.

    },
    // Translate your invoice to your preferred language
    "translate": {

    },
};

easyinvoice.createInvoice(data, function (result) {
    //The response will contain a base64 encoded PDF file
    console.log('PDF base64 string: ', result.pdf);
});

**Comment by VinothGox** [comment]
Any update?
