### ISSUE TITLE
got an error while create invoice

### ISSUE THREAD

**Issue by kazdhicham** [dveldhoen/easyinvoice#121]
**i tried to generate my pdf file** 
 easyinvoice.createInvoice(data, function (result) {
  var pdf = result.pdf;
  fs.writeFileSync("invoice.pdf", pdf, 'base64');
    easyinvoice?.print(result.pdf)

**i got**
{ statusCode: 500, message: 'Internal server error' }
- error unhandledRejection: { source: 'server', message: 'Internal server error' }
- error unhandledRejection: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (node:fs:2338:5)

**Comment by dveldhoen** [comment]
Hi, sorry I just noticed we didn't respond to this issue. Apologies. Are you still experiencing this issue? I will close the issue for now, please let me know and I will reopen the issue.
