### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by mario8754** [dveldhoen/easyinvoice#124]
I cannot create an account to make an API Key. there is an email issue on your website. Can you please fix it?

**Comment by dveldhoen** [comment]
Hi, 

Unfortunately, we are experiencing a disruption in sending emails due to a problem with our email provider.
We are very sorry for the inconvenience and are working around the clock with them to resolve the issue.

**Comment by mario8754** [comment]
is there an possibility to log in? my email is info@ameliewebdesign.nl . I really like to generate an api for my invoices to be generated again

**Comment by dveldhoen** [comment]
I expect the issue will be fixed within the next 1 to 3 hours. Sorry for the inconvenience.

**Comment by dveldhoen** [comment]
Oh, I see the problem has just been resolved.

**Comment by mario8754** [comment]
Nope still no message after an password reset

**Comment by dveldhoen** [comment]
I just tried, the password reset works fine. What error are you getting?

**Comment by mario8754** [comment]
Yes it works, it just took some time. thank you
