### ISSUE TITLE
formatting of numbers

### ISSUE THREAD

**Issue by ncventure** [dveldhoen/easyinvoice#19]
Hi there,

First of all thank you for contributing to the github library. Can we perhaps add formatting to number values? 10000.00 is not formatted as 10,000.00.

Thanks a lot!

**Comment by ncventure** [comment]
Perhaps this is due to european settings, can we add it optionally?

**Comment by dveldhoen** [comment]
Hi, good suggestion! We hadn't considered this yet. Sorry for the late reply by the way. We will look into it as soon as possible!

**Comment by ncventure** [comment]
Thanks a lot!

**Comment by dveldhoen** [comment]
Hi, it took a bit longer than expected but we implemented this just now using the javascript INTL api. Should be working in about 15 minutes from now. I will update the documentation as soon as possible today.
