### ISSUE TITLE
'Module not found' errors when running 'ng build'

### ISSUE THREAD

**Issue by rmthoma** [dveldhoen/easyinvoice#20]
NPM version - 6.14.11
`"webpack": "^4.0.0",`
`"@angular/core": "^11.1.1",`

I have tried to install the npm packages "tty", "zlib" and even the browserify versions of those packages but they did not make a difference.

I also originally had the same errors for 'http', 'https' (solved by adding the following to my package.json:
`"browser": {
    "http": false,
    "https": false
  },
`
The error for 'stream' was fixed by adding the npm package.
The error for 'os' was fixed with a workaround.
The errors for these packages all showed the same as attached. I just cannot fix these last two. It builds fine **without** using `easyinvoice.download('myInvoice.pdf', result.pdf);`. It will build if I use `easyinvoice.createInvoice` with nothing inside the function.

I did see a similar error reported but it was for react native.

![image](https://user-images.githubusercontent.com/13741605/106897595-400f1000-6747-11eb-951f-118b67b56303.png)

**Comment by dveldhoen** [comment]
Hi, and thanks for contacting us. From your error logs I can't really figure out your problem. You are probably trying to use the package in a 'non-browser' environment? Those environments we don't (yet) support with this package.

As a workaround I would suggest calling our API-endpoint directly without using the npm-package. To do this just sent a simple POST request to https://api.easyinvoice.cloud/v1/invoices like so:

`{
    "data": {
"documentTitle": "Receipt"
}
}`

**Comment by dveldhoen** [comment]
We will also make sure to add some REST endpoint documentation soon to help other people who experience the same problems.

**Comment by rmthoma** [comment]
I have used your solution and your API returns the PDF in Base64. Can you recommend any way to convert the Base64 string returned to a PDF file? And thank you, documentation on your endpoints would be very helpful.

**Comment by dveldhoen** [comment]
Sure, have a look at this thread on Stackoverflow. Should point you in the right direction.
https://stackoverflow.com/questions/56483097/decoding-base64-pdf-giving-broken-file

**Comment by dveldhoen** [comment]
Please let us know if you need more help.
