### ISSUE TITLE
Document Title Line Height

### ISSUE THREAD

**Issue by employee451** [dveldhoen/easyinvoice#22]
Hi! When providing a long document title (like "EARNINGS STATEMENT"), the text has to wrap. 
However, it looks like there is an issue with the line height of the document title, since it wraps on top of the first line.

**Comment by dveldhoen** [comment]
Thanks for contacting us, we will look into this and get back to you as soon as possible.

**Comment by dveldhoen** [comment]
Hi, we just fixed this problem. The update should be live in about 15 minutes.
