### ISSUE TITLE
Custom Text for Date and Number

### ISSUE THREAD

**Issue by employee451** [dveldhoen/easyinvoice#23]
It would be great if there was an option for customizing the "Invoice Number" and "Invoice Date" text.
It could simply be optional `dateText` and `numberText` parameters on the `data` object, which default to "Invoice Number" and "Invoice Date".

**Comment by dveldhoen** [comment]
Hi, thanks for contacting us. We will discuss this in our next meeting to see if it fits our package. Will let you know!

**Comment by employee451** [comment]
Thank you for your reply. Please let me know when you have an update on this.

**Comment by employee451** [comment]
Hi again. Have you had the chance to consider this suggestion?😄

**Comment by dveldhoen** [comment]
Hi, out of curiosity what kind of text would you want to put in the respective fields?

**Comment by employee451** [comment]
Hi. We would write "Receipt Number" and "Receipt Date" or "Earnings Statement Number" and "Earnings Statement Date"

**Comment by dveldhoen** [comment]
We are currently working on this. Standby :)

**Comment by dveldhoen** [comment]
Implemented as of now!
