### ISSUE TITLE
Custom Values Not Working

### ISSUE THREAD

**Issue by employee451** [dveldhoen/easyinvoice#25]
Hi there. When trying to add custom values on either the Sender or Client objects, they aren't shown in the invoice.
In my case, I am trying to add the value `taxId` to both the Sender and Sender, but this property is not showing up on the generated PDF.

**Comment by dveldhoen** [comment]
Hi, we just checked but the custom values are working as they should. For an example on how to use this see this Fiddle:
https://jsfiddle.net/easyinvoice/rjtsxhp3/
