### ISSUE TITLE
Module not found: Error: Can't resolve 'http'

### ISSUE THREAD

**Issue by manid6** [dveldhoen/easyinvoice#26]
I am getting the following error after installing and can't fix this can anybody help me with this.

./node_modules/easyinvoice/dist/easyinvoice.js
Module not found: Error: Can't resolve 'http'

**Comment by dveldhoen** [comment]
Are you trying to use the package outside of a browser/nodeJS environment?

**Comment by dveldhoen** [comment]
We currently don't support environments without http support. We will in the future.

Since, you didn't respond I will close this issue for now.
