### ISSUE TITLE
VAT Doesn't displayed & questions

### ISSUE THREAD

**Issue by antoineVIVIES** [dveldhoen/easyinvoice#3]
```
const data = {
                        "currency": "EUR",
                        "taxNotation": "vat", //or gst
                        "marginTop": 25,
                        "marginRight": 25,
                        "marginLeft": 25,
                        "marginBottom": 25,
                        "logo": fs.readFileSync("resources/img/geode_logo.png", { encoding: 'base64' }), //or base64
                        "logoExtension": "png", //only when logo is base64
                        "companyFrom": "Geode",
                        "addressFrom": "Boulevard de la marquette",
                        "zipFrom": "31200",
                        "cityFrom": "Toulouse",
                        "countryFrom": "France",
                        "companyTo": invoice.order.company.name,
                        "addressTo": invoice.order.company.address,
                        "zipTo": invoice.order.company.zipCode,
                        "cityTo": invoice.order.company.address,
                        "countryTo": "France",
                        "invoiceNumber": invoice.invoiceId,
                        "invoiceDate": dateInvoice,
                        "products": [],
                        "bottomNotice": "Kindly pay your invoice within 15 days."
                };
                for (const orderItem of invoice.order.orderItems) {
                        data.products.push({
                                "quantity": orderItem.quantity,
                                "description": orderItem.product.name,
                                "tax": 20,
                                "price": orderItem.product.price
                        });
                }
                return await easyinvoice.createInvoice(data, function (result) {
                        return (result.pdf);
                });
```

I got this config but the VAT isn't displayed at all.

In France, we have other mandatory fields for companies, named siret and siren is it possible to add them easily?
Thanks

**Comment by dveldhoen** [comment]
Hi Antoine,

I'm sorry to hear that. We will have a look at your config straight away. We can look into adding 'siret' and 'siren', but we will need your help in explaining what these values are for and where they should be on the invoice.

Thanks in advance!

**Comment by antoineVIVIES** [comment]
Hi Danny,

They are identification numbers for companies, they have to be just under the companies information.
Like this: https://miro.medium.com/max/1400/1*LW2sjmjFWDFu6KOspFPrkg.png
Thanks for your quick answer!

**Comment by dveldhoen** [comment]
Great, we will do our best to add them in the next 24-48 hours. Off course we want to support our French users as well :). Will also get back on your config ASAP.

**Comment by antoineVIVIES** [comment]
Thanks a lot :) !
I'm waiting for your reply!

**Comment by dveldhoen** [comment]
The vat has been fixed. There was a small bug in the api. Thanks for noticing. One of the developers is now working on the extra fields. I expect the will be added in about 24-48 hours. I'll let you know here when they are added.

One small suggestion on your code, you are using both async and callback notation together. If your environment supports the 'await' notation I would suggest using this code to generate the invoice:

```js
const result = await easyinvoice.createInvoice(data);
return (result.pdf);
```

**Comment by dveldhoen** [comment]
Hi Antoine,

We updated the package so sender and client are both objects. This will provide for a better overview of your data object. Also we added 3 custom fields for both sender and client. So in your case you could use the following notation to define the sender:
```js
"sender": {
        "company": "Sample Corp",
        "address": "Sample Street 123",
        "zip": "1234 AB",
        "city": "Sampletown",
        "country": "Samplecountry"
        "custom1": "Siret: 1234",
        "custom2": "Siren: 5678"
},
```

Please see the updated docs for a full data example: https://www.npmjs.com/package/easyinvoice

**Comment by antoineVIVIES** [comment]
Hi Danny,
I'll try it out now!
thanks for your reactivity :)

**Comment by dveldhoen** [comment]
No problem, please let us know if you experience any other issues. We like to solve issues as agile and fast as we can.
