### ISSUE TITLE
Shipping Fees

### ISSUE THREAD

**Issue by saiteja-konda** [dveldhoen/easyinvoice#30]
what if i wanted to add shipping fees at the end and add it to the total ?

**Comment by dveldhoen** [comment]
Hi, unfortunately this is not possible at the moment. We will take it into consideration for future updates. For now I would suggest putting the shipping fees in with the products.

**Comment by saiteja-konda** [comment]
Thanks for the suggestion @dveldhoen , I'm really glad to use this project is very simple and straight forward
Yes that what i did to move on .

in my application invoice generates along with QR code, it know this is edge case but i suggest you to consider to allow api to accept another image along with logo which can be QR code or Bar code.
