### ISSUE TITLE
Clear the authorization header

### ISSUE THREAD

**Issue by hannesfant** [dveldhoen/easyinvoice#31]
Was trying to use this library and since it's using axios it's interfering with another library. The other lib is setting the global axios auth header, which results in easyinvoice also using the same API key. An easy fix for this would be to specify the Authorization header in each axios request to overwrite any other potential ones for that specific request.

I would do it myself, but I was not quite sure how changes are handled here with your dist.

The API is also denying all requests with an invalid API key, instead of letting through the free requests, like it does when no key is supplied. :)

**Comment by dveldhoen** [comment]
Hi! 

Thanks for letting us know, we didn't come across this before. We changed the import name in our code 
from: const axions = require('axios'); 
to: const axiosForEasyInvoice = require('axios');

We expect this should fix your problem. Would you be willing to verify this for us? That would be great.

**Comment by hannesfant** [comment]
Hey, that doesn't seem to have worked as they're still using the same axios package. I think the easiest and most efficient way would be to just manually override the Authorization header in each request.

**Comment by hannesfant** [comment]
Your change unfortunately didn't fix it, but creating a new Axios instance does. I've created a pull request for it. :)

**Comment by dveldhoen** [comment]
Thanks for your pull-request. A few minutes before that I added Authorization: null to the request, which seemed to work. But your suggestion is much cleaner! Very much appreciated. I will remove my own fix in the next patch.

**Comment by dveldhoen** [comment]
Just to clarify, it's working now for you? :)

**Comment by hannesfant** [comment]
Yep, working perfectly!

**Comment by dveldhoen** [comment]
Awesome!
