### ISSUE TITLE
Missing customerID and IBAN for the Seller

### ISSUE THREAD

**Issue by XxQuickSilverZz** [dveldhoen/easyinvoice#35]
![image](https://user-images.githubusercontent.com/55958378/119671898-7083d280-be3a-11eb-8f9b-f8011db41ac6.png)

**Comment by employee451** [comment]
You can add custom values for the seller by adding `customX` properties to the `sender` property. 
Example:


    sender: {
        // normal values
        custom1: "Customer ID: 1234"
        custom2: "IBAN: xxxxxxxxxxx"
        // custom3, etc.
    }

**Comment by dveldhoen** [comment]
Above response solves this issue. We will look into supporting custom values on the proposed location.
