### ISSUE TITLE
Feature Request - Due Date + calculation results

### ISSUE THREAD

**Issue by mits87** [dveldhoen/easyinvoice#38]
Hi, 
Thanks for the really nice library.

Would be super nice if you can add:
- Invoice Due Date attribute
- some possibility to returns all calculation results like total etc.

Thanks in advance.

**Comment by Tolfx** [comment]
Saw this issue, will it be possible to have due dates in the future?

**Comment by Tolfx** [comment]
Thus since I found a solution I like to share..
Add in client object:
```js
"custom1": `
                <div style="
                position: fixed;
                right: 28;
                top: 213;
                ">
                    <strong>Due Date:</strong> Date
                </div>`,
```

Result:
![image](https://user-images.githubusercontent.com/57797792/141830398-2441fe50-e608-43e5-aed6-0dbc7fa7dfc3.png)

**Comment by dveldhoen** [comment]
Thanks for your reply! This is exactly how we intended the custom fields. We will add due date later as standard field.

**Comment by dveldhoen** [comment]
Hi, we added the calculation results to the returned object! Please let us know if anything is missing.
