### ISSUE TITLE
Invalid main field in package.json

### ISSUE THREAD

**Issue by employee451** [dveldhoen/easyinvoice#44]
(node:90936) [DEP0128] DeprecationWarning: Invalid 'main' field in 'node_modules/easyinvoice/package.json' of '/dist/easyinvoice.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by dveldhoen** [comment]
This should be fixed, can you verify?

**Comment by dveldhoen** [comment]
Will close since we didn't get a response. Also bug seems to be fixed. No deprecation warning in Node 16.
