### ISSUE TITLE
Changing invoice template.

### ISSUE THREAD

**Issue by AlexLeka98** [dveldhoen/easyinvoice#45]
How can I change the invoice template? For example how can I change the "Products" into "Services" on the pdf, or get rid of the "Quanity" column?

**Comment by koniuszy** [comment]
u can use `translate` key in `InvoiceData` to map `Products` into `Services`

**Comment by mohssineAboutaj** [comment]
like this
![image](https://user-images.githubusercontent.com/30943833/143858445-854cee10-7ef2-4549-bb62-1e76d807b8cb.png)
thank you @koniuszy

**Comment by dveldhoen** [comment]
We will look into adding an option to hide the quantity column. For now this is not possible. I will put it on the feature list! Thanks!
