### ISSUE TITLE
createInvoice method returning error

### ISSUE THREAD

**Issue by chris-cornwall** [dveldhoen/easyinvoice#50]
Hi there, thanks for the great work on this package. It's super easy to use! However, I've just started to receive an error when trying to create an invoice:

`{
error: 'SequelizeHostNotFoundError', 
message: 'getaddrinfo ENOTFOUND database-private-write.easyinvoice.cloud',
 errorId: '9671c6057739414db25022a250c82c3a'
 }`
 
I haven't made any code changes recently and I haven't found any other issues with anything similar, do you have any idea what may be causing this?

Cheers!

**Comment by dveldhoen** [comment]
Hi, apologies. We had a small disturbance in our API. Should be fixed now.

**Comment by chris-cornwall** [comment]
Okay, thanks for the quick reply!
