### ISSUE TITLE
Support for thermal paper

### ISSUE THREAD

**Issue by sachi097** [dveldhoen/easyinvoice#53]
Hi @dveldhoen 

Thank you for this awesome repo. I have been using easyinvoice since a year now and only complaint I have is providing an option for the page size to 80mm X 60mm (thermal paper) used for credit card printing or in the retail shops.

Could you please add thermal paper size to the page format options list.

**Comment by dveldhoen** [comment]
Hi @sachi097!

Thanks for the kind words. Always nice to hear. 
Also feature requests is something we welcome! I will look into the possibilities and get back to you.

**Comment by sachi097** [comment]
@dveldhoen  thanks for the quick response. This is what makes this repo stand out.

I will be waiting for the findings on the matter.

**Comment by dveldhoen** [comment]
We looked into the possibilities and we are able to provide options for width, height and orientation (portrait/landscape). Will try to release them this week into update 2.3.0. I will let you know once it's published. Will keep this issue open until we do.

**Comment by dveldhoen** [comment]
I'm really curious by the way how Easy Invoice would look on thermal paper. Once you manage this, could you share your findings and possibly pictures with us? Perhaps we could even add this to the documentation, might help others.

**Comment by sachi097** [comment]
@dveldhoen  I am eagerly waiting for the release and excited to try Easy Invoice on the thermal paper. I will surely, share my findings. Now I feel that I should have raised this issue long time back when I started to use Easy Invoice. But I tried workarounds like converting A4 to thermal paper but this destroyed text clarity. Let's hope with the new release text clarity is maintained since this would not involve conversions from A4 to thermal paper.

I know I am asking too much, but it would also be very helpful if you could provide an option to include discounts and Service Charges below Subtotal section. And reduce the discounts and Service Charges in the Total. Again I thought to try a workaround for this, using Tax section but Taxes adds up to the Subtotal. So there should be an option for reduction/subtraction too.

Please let me know if I am not clear regarding the discounts and service charges.

**Comment by dveldhoen** [comment]
@sachi097 I am interested in adding discounts and service charges. Though I have to take into account that it's applicable to every business use case. Let's take it one step at a time and first implement the sizing. Perhaps you could help me out with creating a new issue already for the discount and service charges. After I release 2.3.0 we'll discuss and look into the possibilities. I do need some more information on this.

**Comment by sachi097** [comment]
@dveldhoen  Sure I will create new issue for the same.

And about the question for discounts & service charges for every use case, we can keep these fields as optional like the Taxes. Taxes add up only when tax field under products is a positive number like wise discounts & service charges can be made optional fields i.e. we display the discounts & service charges and reduce the value from the Total only when these field have positive numbers. And for businesses which do not want to make use of these fields can set 0 as value for these fields so that nothing changes to them.

**Comment by dveldhoen** [comment]
Hi, 

Functionality has been added. Please let us know your findings, since we didn't take much time to test it.
If you are able to make a valid template for thermal paper can you post the settings you used? Thanks in advance.

Hope to hear from you soon.

**Comment by dveldhoen** [comment]
*Documentation can be found in NPM Readme

**Comment by sachi097** [comment]
Hello Dveldhoen,

Sorry for the late reply. After trial and error I managed to print the
invoice on thermal paper. This still needs correction in the format. I am
attaching the template, pdf and the print for your reference.

Template:
const data = {
    "images": {
      "logo": "https://public.easyinvoice.cloud/img/logo_en_original.png"
    },
    "sender": {
      "company": "Sample Corp",
      "address": "Sample Street 123",
      "zip": "1234 AB",
      "city": "Sampletown",
      "country": "Samplecountry",
      "custom1": "Sale: 10% By: ZwellStar"
    },
    "client": {
      "company": "Client Corp",
      "address": "Clientstreet 456",
      "zip": "4567 CD",
      "city": "Clientcity",
      "country": "Clientcountry"
    },
    "information": {
      "number": "ZFY1hmBb",
      "date": "1.1.2022",
      "due-date": "1.1.2022"
    },
    "products": [
      {
        "quantity": "2",
        "description": "Chicken Dum Biriyani",
        "tax-rate": 0,
        "price": 300
      },
      {
        "quantity": "4",
        "description": "Grilled Panner Veg Rolls",
        "tax-rate": 0,
        "price": 2500
      }
    ],
    "bottom-notice": "Settled Amount = 200 - 5%(Service Charge) -
17(Delivery Charge) = 173",
    "settings": {
      "currency": "INR",
      "locale": "en-IN",
      "tax-notation": "gst",
      "margin-top": 0,
      "margin-right": 0,
      "margin-left": 0,
      "margin-bottom": 0,
      "height": "750px",
      "width": "80mm"
    },
    "translate": {
      "number": "ID", // Defaults to 'Number'
      "date": "DT", // Default to 'Date'
      "due-date": "DDT", // Defaults to 'Due Date'
      "products": "Itm", // Defaults to 'Products'
      "quantity": "Qty", // Default to 'Quantity'
      "price": "Amt", // Defaults to 'Price'
      "product-total": "Ttl", // Defaults to 'Total'
    }
  };

**Comment by sachi097** [comment]
Hi @dveldhoen 

Sorry for the late response. After trial and error I managed to print the invoice on thermal paper. This still needs correction in the format. I am attaching the template, pdf and the print for your reference.

> const data = {
>     "images": {
>       "logo": "https://public.easyinvoice.cloud/img/logo_en_original.png"
>     },
>     "sender": {
>       "company": "Sample Corp",
>       "address": "Sample Street 123",
>       "zip": "1234 AB",
>       "city": "Sampletown",
>       "country": "Samplecountry",
>       "custom1": "Sale: 10% By: ZwellStar"
>     },
>     "client": {
>       "company": "Client Corp",
>       "address": "Clientstreet 456",
>       "zip": "4567 CD",
>       "city": "Clientcity",
>       "country": "Clientcountry"
>     },
>     "information": {
>       "number": "ZFY1hmBb",
>       "date": "1.1.2022",
>       "due-date": "1.1.2022"
>     },
>     "products": [
>       {
>         "quantity": "2",
>         "description": "Chicken Dum Biriyani",
>         "tax-rate": 0,
>         "price": 300
>       },
>       {
>         "quantity": "4",
>         "description": "Grilled Panner Veg Rolls",
>         "tax-rate": 0,
>         "price": 2500
>       }
>     ],
>     "bottom-notice": "Settled Amount = 200 - 5%(Service Charge) - 17(Delivery Charge) = 173",
>     "settings": {
>       "currency": "INR",
>       "locale": "en-IN",
>       "tax-notation": "gst",
>       "margin-top": 0,
>       "margin-right": 0,
>       "margin-left": 0,
>       "margin-bottom": 0,
>       "height": "750px",
>       "width": "80mm"
>     },
>     "translate": {
>       "number": "ID", // Defaults to 'Number'
>       "date": "DT", // Default to 'Date'
>       "due-date": "DDT", // Defaults to 'Due Date'
>       "products": "Itm", // Defaults to 'Products'
>       "quantity": "Qty", // Default to 'Quantity'
>       "price": "Amt", // Defaults to 'Price'
>       "product-total": "Ttl", // Defaults to 'Total'
>     }
> };

[invoices_regi_test122566.pdf](https://github.com/dveldhoen/easyinvoice/files/8204452/invoices_regi_test122566.pdf)[](url)
[thermal](https://user-images.githubusercontent.com/36642643/157206763-fcc9f332-6345-4205-894c-3d3d44267dc6.jpg)

**Comment by dveldhoen** [comment]
Thanks! I appreciate the reply. I will look into optimizing Easy Invoice in the future for thermal paper.
Perhaps things like font-size, etc. could optimize it even more.

**Comment by dveldhoen** [comment]
But this looks great, can I use your picture and template in our NPM documentation?

**Comment by sachi097** [comment]
Hi @dveldhoen  do we have an option to set font-size? If yes how? Because I didn't find it anywhere in the documentation.
And regarding the picture, how about you give me sometime like a week so that I can print the page and get the image correctly for the documentation?

**Comment by dveldhoen** [comment]
For now the only option to change font-size is to alter the template with css, but I could add an option for font-size that supports the managed template.

Regarding the picture, sure that would be great. I'm not in a rush. Thanks for the efforts!

**Comment by sachi097** [comment]
Hi @dveldhoen 

Please find latest template and attachment. Feel free to include the pdf for documentation.
```
const data = {
    "images": {
      "logo": ""
    },
    "sender": {
      "company": "ABC Corp",
      "address": "Vidyagiri",
      "zip": "587102",
      "city": "Bagalkot",
      "country": "INDIA"
    },
    "client": {
      "company": "ABC Customer",
      "address": "Vidyagiri",
      "zip": "587102",
      "city": "Bagalkot",
      "country": "INDIA"
    },
    "information": {
      "number": "ZFY1hmBb",
      "date": "16.03.2022",
      "due-date": "16.03.2022"
    },
    "products": [
      {
        "quantity": "1",
        "description": "Chicken Dum Biriyani",
        "tax-rate": 0,
        "price": 175
      },
      {
        "quantity": "2",
        "description": "Grilled Panner Veg Rolls",
        "tax-rate": 0,
        "price": 120
      }
    ],
    "bottom-notice": "Settled Amount = 415 - 30(Service Charge) - 6(Delivery Charge) = 379",
    "settings": {
      "currency": "INR",
      "locale": "en-IN",
      "tax-notation": "gst",
      "margin-top": 0,
      "margin-right": 0,
      "margin-left": 0,
      "margin-bottom": 0,
      "height": "750px",
      "width": "80mm"
    },
    "translate": {
      "number": "ID", // Defaults to 'Number'
      "date": "DT", // Default to 'Date'
      "due-date": "DDT", // Defaults to 'Due Date'
      "products": "Itm", // Defaults to 'Products'
      "quantity": "Qty", // Default to 'Quantity'
      "price": "Amt", // Defaults to 'Price'
      "product-total": "Ttl", // Defaults to 'Total'
    }
  };
```
[thermal_easyinvoice.pdf](https://github.com/dveldhoen/easyinvoice/files/8261923/thermal_easyinvoice.pdf)

Also, I found out an issue - Indian Currency (₹) is not reflecting in the invoice. Same can be seen in the attached pdf. Please look into this issue.
