### ISSUE TITLE
Support for deduction/subtraction for the Subtotal amount

### ISSUE THREAD

**Issue by sachi097** [dveldhoen/easyinvoice#54]
Hi @dveldhoen

Please consider below use case.

A business is running up a X% discount(sale) on total order value. Also it charges Y% as a service charge to a customer. Now, these factor fall under deductions to Subtotal value.
------------------------------------------------------------------------------------------------------------------------------------------------
Example 1: Let X=5 & Y=2
Product P1 -> Price 2500INR, Quantity: 1, GST(Tax) 12%
Product P2 -> Price 1000INR, Quantity: 1, GST(Tax) 0%

Price P1 * Quantity P1 = S1: 2500 INR
Price P2 * Quantity P2 = S2: 1000 INR

S1 + S2  = Subtotal: 3500 INR
GST 12% of S1: 420 INR <------- optional field (product may/may not undergo tax depending upon type)
Discount 5% of Subtotal: 175 INR <------- optional field (business may/may not provide discount/sale)
Service Charge 2% of Subtotal: 70 INR <------ optional field (business may/may not charge service charge)

Total: 3675 INR (Subtotal + GST - Discount - Service Charge)
------------------------------------------------------------------------------------------------------------------------------------------------

Example 2: Let X=0 & Y=2
Product P1 -> Price 2500INR, Quantity: 1, GST(Tax) 0%
Product P2 -> Price 1000INR, Quantity: 1, GST(Tax) 0%

Price P1 * Quantity P1 = S1: 2500 INR
Price P2 * Quantity P2 = S2: 1000 INR

S1 + S2  = Subtotal: 3500 INR
Service Charge 2% of Subtotal: 70 INR <------ optional field (business may/may not charge service charge)

Total: 3430 INR (Subtotal - Service Charge)
------------------------------------------------------------------------------------------------------------------------------------------------

Example 3: Let X=0 & Y=0
Product P1 -> Price 2500INR, Quantity: 1, GST(Tax) 0%
Product P2 -> Price 1000INR, Quantity: 1, GST(Tax) 0%

Price P1 * Quantity P1 = S1: 2500 INR
Price P2 * Quantity P2 = S2: 1000 INR

S1 + S2  = Subtotal: 3500 INR

Total: 3500 INR (Subtotal)
------------------------------------------------------------------------------------------------------------------------------------------------

Hence, deductions (Discounts & Service Charges) play an important role in invoicing/billing.

Please consider adding these optional fields. I am looking forward for positive response from your end. Also excited to discuss more business use cases in details.

**Comment by dveldhoen** [comment]
Marked as feature an put noted for future updates.
