### ISSUE TITLE
How to remove tax-rate

### ISSUE THREAD

**Issue by adamfakrullah** [dveldhoen/easyinvoice#55]
Hi, can i know how to remove tax-rate and using only one tax for all products? Thank you

**Comment by dveldhoen** [comment]
Hi, if you leave the tax rate at 0 it should remain hidden. If you want the same rate for all products, you will have to specify the same rate per product. There is no global option.

**Comment by adamfakrullah** [comment]
I want to ask something. Maybe a silly question. can i know how to mapping v-model for tax-rate because it has ' ' symbol for Vuejs. Thank you

**Comment by dveldhoen** [comment]
v-model="row['tax-rate']"
