### ISSUE TITLE
Translate to Japanese word.

### ISSUE THREAD

**Issue by adamfakrullah** [dveldhoen/easyinvoice#56]
translate: {  invoice: 'Invoice',  
number: 'No.',
date: '請求日',
subtotal: '小計',
products: '商品名/品名',
quantity: '数量', 
price: '金額',
total: '合計' }

Hi, I already change word to Japanese in translate part but its not reflected in pdf file. Can you help me? Thank you

**Comment by adamfakrullah** [comment]
Is there any update regarding to this issue?Thank you

**Comment by dveldhoen** [comment]
Hi, to my surprise this indeed does not work. We will investigate the issue and get back to you

**Comment by adamfakrullah** [comment]
Hope u can fix it. Thanks

**Comment by adamfakrullah** [comment]
Hi. is it the package already can translate to Japanese language?

**Comment by dveldhoen** [comment]
Noted and will be fixed in the future. Closing for now.
