### ISSUE TITLE
It would be really nice if you could change the title "Invoice" to be "Receipt" or something else instead.

### ISSUE THREAD

**Issue by JVPartanen** [dveldhoen/easyinvoice#6]

**Comment by dveldhoen** [comment]
Done! Update is being pushed as we speak. Should work within like 15 minutes.
Thanks for your feedback! Please let us know if we can improve this package any other way.

**Comment by dveldhoen** [comment]
Please view the docs for the 'documentTitle' parameter. This will let you change the 'Invoice' title.
