### ISSUE TITLE
Japanese language

### ISSUE THREAD

**Issue by adamfakrullah** [dveldhoen/easyinvoice#60]
translate: { invoice: 'Invoice',
number: 'No.',
date: '請求日',
subtotal: '小計',
products: '商品名/品名',
quantity: '数量',
price: '金額',
total: '合計' }

Hi, I already change word to Japanese in translate part but its not reflected in pdf file. I hope you can help me. Thank you sir

**Comment by dveldhoen** [comment]
Duplicate of #56
