### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by gwendal5** [dveldhoen/easyinvoice#61]
Hi

I'm having an issue using the package, I get the error
```bash
TypeError: Cannot read properties of undefined (reading 'data')
    at /home/gwendal/Documents/SvelteKit/easyinvoice/node_modules/easyinvoice/dist/easyinvoice.min.js:1:17753
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

My code is this : 
```bash
var easyinvoice = require('easyinvoice');
var fs = require('fs');

var data = {};

easyinvoice.createInvoice(data, function (result) {
    fs.writeFileSync("invoice.pdf", pdf, 'base64');
});
```

**Comment by dveldhoen** [comment]
Hi,

Please try this:

`var easyinvoice = require('easyinvoice');
var fs = require('fs');

var data = {};

easyinvoice.createInvoice(data, function (result) {
    fs.writeFileSync("invoice.pdf", result.pdf, 'base64');
});`

The result object contains the pdf. So in your example replace 'pdf' with 'result.pdf'. That should fix it.
