### ISSUE TITLE
API rate limits

### ISSUE THREAD

**Issue by jeremyrajan** [dveldhoen/easyinvoice#63]
Hello!

We would like to try your library, but from what we see it's calling an API endpoint to generate the PDFs. Could you please let us know about the rate limits?

Thanks,
Jeremy

**Comment by dveldhoen** [comment]
Hi there,

Should be about 150 calls per 15 minutes. Later this year we will introduce plans which will allow you to use more than that if required.

Kind regards,

Danny Veldhoen
