### ISSUE TITLE
Endpoint request timed out

### ISSUE THREAD

**Issue by goyslee** [dveldhoen/easyinvoice#64]
When I set my own logo or use my own background, this is the error message I get: `{message: 'Endpoint request timed out'}`

I cannot see what is causing this.

**Comment by Azamat-Shogen** [comment]
I cant get the any logo to display, even following a youtube tutorial on this. Plus invoice number, date , due date, total , and bottomNotice are blank.

**Comment by b2bPrasad** [comment]
@goyslee are you using a base64 image? I got the same error while using that. I switched to using an image URL and it worked.

**Comment by goyslee** [comment]
> @goyslee are you using a base64 image? I got the same error while using that. I switched to using an image URL and it worked.

I try to use base64 PNG file. So is there no workaround with base64 image/pdf usage?

**Comment by dveldhoen** [comment]
Hi all, and sorry for the late response. I'm sorry if base64 is not working for you, it should be. Can you please send the data object you use to create the invoice to me. You can also send it privately to info@easyinvoice.cloud if so desired.

We will make sure to fix it then. Thanks in advance.

**Comment by goyslee** [comment]
Hi, here is the object i use for easyinvoice npm package.

var data = {
// Customize enables you to provide your own templates
// Please review the documentation for instructions and examples
"customize": {
// "template": fs.readFileSync('template.html', 'base64') // Must be base64
encoded html
},
"images": {
// The logo on top of your invoice
"logo": fs.readFileSync("img/logo_en_original.png", "base64"),
// The invoice background
// "background": fs.readFileSync("pdf/background.pdf", "base64")
},
// Your own data
"sender": {
"company": "Kindla's Computers",
"address": "Kemp House, 152 - 160, City Road ",
"zip": "EC1V 2NX",
"city": "London",
"country": "United Kingdom"
//"custom1": "custom value 1",
//"custom2": "custom value 2",
//"custom3": "custom value 3"
},
// Your recipient
"client": {
"company": `${req.body.quote.invoiceName}`,
"address": `${req.body.quote.address}`,
"zip": `${req.body.quote.postCode}`,
"city": `${req.body.quote.city}`,
"country": `${req.body.quote.country}`
// "custom1": "custom value 1",
// "custom2": "custom value 2",
// "custom3": "custom value 3"
},
"information": {
// Invoice number
"number": invoiceNumber,
// Invoice data
"date": `${m.local().format("DD MMM YYYY")}`,
// Invoice due date
"due-date": `${m.local().format("DD MMM YYYY")} <br><b>Time: </b>${myPdfDate
.toLocaleTimeString()}`,
},
// The products you would like to see on your invoice
// Total values are being calculated automatically
"products": [
{
"quantity": req.body.quote.q1,
"description": req.body.quote.description1,
"tax-rate": 0,
"price": req.body.quote.price1
},
{

"quantity": `${req.body.quote.q2 || empty}`,
"description": `${req.body.quote.description2 || empty}`,
"tax-rate": 0,
"price": `${req.body.quote.price2 || empty}`,

}
// {
// "quantity": 4.5678,
// "description": "Product 3",
// "tax-rate": 21,
// "price": 6324.453456
// }
],
// The message you would like to display on the bottom of your invoice
"bottom-notice": "Thank you for choosing Kindla's Computers.",
// Settings to customize your invoice
"settings": {
"currency": "GPB", // See documentation 'Locales and Currency' for more
info. Leave empty for no currency.
// "locale": "nl-NL", // Defaults to en-US, used for number formatting (See
documentation 'Locales and Currency')
// "tax-notation": "gst", // Defaults to 'vat'
// "margin-top": 25, // Defaults to '25'
// "margin-right": 25, // Defaults to '25'
// "margin-left": 25, // Defaults to '25'
// "margin-bottom": 25, // Defaults to '25'
// "format": "A4", // Defaults to A4, options: A3, A4, A5, Legal, Letter,
Tabloid
// "height": "1000px", // allowed units: mm, cm, in, px
// "width": "500px", // allowed units: mm, cm, in, px
// "orientation": "landscape", // portrait or landscape, defaults to
portrait
},
// Translate your invoice to your preferred language
"translate": {
// "invoice": "FACTUUR", // Default to 'INVOICE'
// "number": "Nummer", // Defaults to 'Number'
// "date": "Datum", // Default to 'Date'
// "due-date": "Verloopdatum", // Defaults to 'Due Date'
// "subtotal": "Subtotaal", // Defaults to 'Subtotal'
// "products": "Producten", // Defaults to 'Products'
// "quantity": "Aantal", // Default to 'Quantity'
// "price": "Prijs", // Defaults to 'Price'
// "product-total": "Totaal", // Defaults to 'Total'
// "total": "Totaal" // Defaults to 'Total'
},
};

**Comment by dveldhoen** [comment]
Good news everyone! The problem has been found and fixed. The deployment pipeline is running and should be finished in about 15 minutes. You can start using base64 images again as documented on NPM. Sorry for the inconvenience and the delay.

**Comment by goyslee** [comment]
Thank you!

I have tested it already and can confirm it is now working with base64 images and pdf files.

**Comment by dveldhoen** [comment]
Great to hear! Thanks for confirming!
