### ISSUE TITLE
VAT not being calculated correctly?

### ISSUE THREAD

**Issue by DennisSpek** [dveldhoen/easyinvoice#67]
Alright, so when I make a test order with 2 items and include some kind of discount code, VAT seems to not be calculated correctly. 

Item A costs 120 EUR and item B costs 180 EUR. This makes 300. Now if you exclude the discount of 60, you'll be back at 240 EUR.

Now if you have 21% Tax running on both item A and B, you'll be charged with an additional 63 EUR for the taxes. I am not sure about this but I believe that is wrong. You are calculating taxes over an amount that is not being payed. 240 * 1,21 = 290,4. Not 303

**Comment by dveldhoen** [comment]
Hi, can you copy your config for me? If we can reproduce and understand your issue it will be easier to fix. Thanks!
