### ISSUE TITLE
after installing the npm i easyinvoice getting those error, I tried it's not work

### ISSUE THREAD

**Issue by raselmahmud22** [dveldhoen/easyinvoice#68]
Please let me know if you have another solution for React js, thanks

`BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
	- install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "http": false }

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
	- install 'https-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "https": false }`

**Comment by raselmahmud22** [comment]
<img width="960" alt="problem" src="https://user-images.githubusercontent.com/61463085/175667070-a6ca8272-bade-403c-8e97-3705a535aec9.png">

**Comment by dveldhoen** [comment]
Thank you for reporting this problem. We will try to look into this.

**Comment by dveldhoen** [comment]
Can you solve your error by installing 'url'?
`npm i url`

**Comment by dveldhoen** [comment]
No answer, closing for now.
