### ISSUE TITLE
POST our data to easyinvoice api? 

### ISSUE THREAD

**Issue by alperdemirci** [dveldhoen/easyinvoice#73]
Hi,
Thank you for creating this package. I see that in createInvoice() method, the invoice data is being POST to easyinvoice api

Is there a reason why such an action is taken for each createInvoice method call?

Or is this package only intended for EasyInvoice.com use? 

Thanks

**Comment by dveldhoen** [comment]
Apologies for the late response. This package is indeed linked to easyinvoice.cloud (not .com). Since this is a paid product, we cannot make our code public.
