### ISSUE TITLE
Download invoice blob:

### ISSUE THREAD

**Issue by lukaszbacik** [dveldhoen/easyinvoice#74]
Welcome.
I have a problem downloading a PDF on a mobile device.
My code:
```
easyinvoice.createInvoice(data, function (result) {
  easyinvoice.download("invoice.pdf", result.pdf);
});
```

It generates the PDF correctly, but it is not possible to download it on the iPhone device (Safari and Firefox) because I get the format "blob:".

How can I correct this?

**Comment by dveldhoen** [comment]
Hello, what you are receiving is a base64 encoded string. You should decode this string and then you can use it however you like. How you manage this on your desired platform is up to you.
