### ISSUE TITLE
Custom Columns Names for invoice products

### ISSUE THREAD

**Issue by Eternity-Brothers** [dveldhoen/easyinvoice#8]
It would be nice to be able to use customer column names when specifying invoice entries.

**Comment by dveldhoen** [comment]
Hi! Thanks for reaching out to us. We are always looking to improve. Could you specify your wishes a bit more? We don’t quite understand yet. Thanks!

**Comment by Eternity-Brothers** [comment]
How do I specify different column names on the invoice items, e.g
```
    "products": [{
        "quantity": "2",
        "description": "Test1",
        "tax": 6,
        "price": 33.87,
        "Custom Column 1": "column value",
        "Custom Column 2": "column value",

      },
      {
        "quantity": "4",
        "description": "Test2",
        "tax": 21,
        "price": 10.45,
        "Custom Column 1": "column value",
        "Custom Column 2": "column value",
      }
    ],
```
It would also be very helpful to implement different column names.

**Comment by dveldhoen** [comment]
Nice suggestion! We will see wat we can do. The devs are on holiday for a week, but we will pick it up asap.

**Comment by KrzysZG37** [comment]
I subscribe to it all. It would be nice to have possibility to customize static fields, as  currently i cannot translate them from application.

**Comment by dveldhoen** [comment]
We noted this down as a feature request for now. I cannot guarantee a timeline on it. Be sure to check frequently for updates. Thanks for the feedback!
