### ISSUE TITLE
easyinvoice.createInvoice is not a function: Node js

### ISSUE THREAD

**Issue by rishabh-arch** [dveldhoen/easyinvoice#80]
after version 3.0.0, easyinvoice shows the empty object in the console.

`var easyinvoice = require('easyinvoice');
console.log(easyinvoice); // output: {}
 `

**Comment by dveldhoen** [comment]
Thanks for notifying us. I was able to reproduce. We will fix it in 3.0.3.

**Comment by dveldhoen** [comment]
We fixed the issues. Please use version 3.0.4.
