### ISSUE TITLE
Unhandled Rejection (TypeError): easyinvoice is not a constructor

### ISSUE THREAD

**Issue by ycymycym** [dveldhoen/easyinvoice#81]
has a issue in react  ts file,
Unhandled Rejection (TypeError): easyinvoice is not a constructor

**Comment by ycymycym** [comment]
I had changed impor like this,
import easyinvoice from 'easyinvoice/src/lib/easyinvoice';

and then
 console.log(easyinvoice);
  const result = await easyinvoice.createInvoice(data);
  
  report
  Unhandled Rejection (TypeError): easyinvoice.createInvoice is not a function
  
      "easyinvoice": "^3.0.4",

**Comment by dveldhoen** [comment]
Thank you for letting us know. We will try to fix this in the next 24 hours.

**Comment by dveldhoen** [comment]
Fixed now in 3.0.5. Please let me know if this fixed your issue. Thank you in advance! Have a nice day.

**Comment by dveldhoen** [comment]
It seems NPM has some issues making the latest publishes available. The version should be available soon thought.

**Comment by dveldhoen** [comment]
NPM is back up, package is available.
