### ISSUE TITLE
easyinvoice.js:29 Uncaught (in promise) TypeError: axios_1.default.create is not a function

### ISSUE THREAD

**Issue by LouisMuriuki** [dveldhoen/easyinvoice#85]
i am using it in react as follows

`import easyinvoice from "easyinvoice";`

  `const DownloadInvoice = (data:any) => {
    easyinvoice.createInvoice(data, function (result: { pdf: string | undefined; }) {
      easyinvoice.download("Invoice.pdf", result.pdf);
    });
  };`
  
  but when i try to download i get the error
  easyinvoice.js:29 Uncaught (in promise) TypeError: axios_1.default.create is not a function

**Comment by MitkoAntov** [comment]
Try the async/await way, I don't have any problems. Also check if you have installed the latest version of the package

**Comment by dveldhoen** [comment]
I just tried it using promises, without async/await. Also works fine:
```js
 easyinvoice.createInvoice({}).then((result)=>{
            easyinvoice.download("test.pdf", result.pdf);
        });
```

**Comment by LouisMuriuki** [comment]
@dveldhoen I still get the error, iam on the latest version 3.0.10, is there any extra step? 
I import from react then create and download the invoice as shown on my code above.
The data object is as same as you have provided in the example

**Comment by dveldhoen** [comment]
Or start from on of our samples in the documentation.

**Comment by LouisMuriuki** [comment]
`
 easyinvoice.createInvoice({}).then((result) => {
      easyinvoice.download("test.pdf", result.pdf);
    });
`
This exactly what my code looks like ,its in a parent functions that runs onClick, iam certain this is what the documentation looks like,did i miss something?

**Comment by LouisMuriuki** [comment]
yes i did

**Comment by dveldhoen** [comment]
Are you using an old Axios version perhaps? Can you try updating that?

**Comment by dveldhoen** [comment]
Or does it fix it when you install @types/axios?

**Comment by LouisMuriuki** [comment]
issue persists, in my project i have to use --legacy-peer-deps while adding some other dependancies, might that be an issue?

**Comment by dveldhoen** [comment]
Could be, it's never recommended anyway to use that prop. Better to resolve the actual issues. I'm looking if I can easily replace axios with the native fetch api. This will probably also fix your issue and make the package smaller as well.

**Comment by dveldhoen** [comment]
I just looked into it, but it has more implications than I thought since only the latest Node versions support the fetch api. And I have to consider compatibility, with both browsers and earlier node versions. I think you are better off fixing your legacy peer deps issues.

**Comment by dveldhoen** [comment]
Probably if you lookup axios in your node_modules it will show you a version below v1. Which is probably not campatible. We use axios@^1

**Comment by dveldhoen** [comment]
And this conflict is caused by legacy-peer-deps. Since it will ignore package dependencies just to solve some errors.

**Comment by LouisMuriuki** [comment]
in my node_modules/axios/package.json it shows version as 1.3.4

**Comment by dveldhoen** [comment]
By the way, downgrading to easyinvoice@^2 will use an older axios version. Which could also solve your issue. Though the api v2 is calling will be deprecated next year. So I don't recommend using older versions.

**Comment by LouisMuriuki** [comment]
okay, I will test it out and get back to you
