### ISSUE TITLE
  ^  Error: Cannot find module 'pdfjs-dist' Require stack:

### ISSUE THREAD

**Issue by ksheetal** [dveldhoen/easyinvoice#87]
After installing the npm package I am getting this error. any solution?

**Comment by dveldhoen** [comment]
Yes, install npm i pdfjs-dist.

**Comment by ksheetal** [comment]
Thanks for the response but I tried this too. but getting issues with pdfjs-dist. Any help on this? 

 const password = src.password ?? null;
                                 ^
SyntaxError: Unexpected token '?'

**Comment by dveldhoen** [comment]
That doesn't sound like an easyinvoice or pdfjs-dist issue. So sorry, can't help you there.

**Comment by ksheetal** [comment]
this issue is coming after installing pdfjs-dist package only. anyway, thanks for your time.

**Comment by ksheetal** [comment]
This issue was coming because of the older node version. resolved now.
