### ISSUE TITLE
easyinvoice.createInvoice is not a function. 

### ISSUE THREAD

**Issue by Ariel-1979** [dveldhoen/easyinvoice#88]
Hello. I am using 'easyinvoice' in development with ViteJs and everything works as expected. Performing npm run build in Vite creates the code for production, but when running the app, it throws this code.

Uncaught TypeError: easyinvoice_1.createInvoice is not a function
    at downloadInvoice (index.03cdb2f8.js:139:30299)
    at onClick (index.03cdb2f8.js:139:31566)
    at Object.Nb (index.03cdb2f8.js:29:9920)
    at Tb (index.03cdb2f8.js:29:10079)
    at Ub (index.03cdb2f8.js:29:10141)
    at nf (index.03cdb2f8.js:29:31775)
    at se (index.03cdb2f8.js:29:32224)
    at index.03cdb2f8.js:29:37360
    at Rk (index.03cdb2f8.js:32:38040)
    at Jb (index.03cdb2f8.js:29:9049)

In development, everything works perfectly, but when I do the npm run build, it stops working.

extension of package.json

	"scripts": {
		"dev": "vite",
		"build": "vite build",
		"preview": "vite preview",
		"format": "prettier --write .",
		"lint": "eslint . --ext .js,.jsx --fix"
	},
	"dependencies": {
		"easyinvoice": "^3.0.12",
		"pdfjs": "^2.4.7",
		"react": "18.2.0",
		"react-dom": "18.2.0",
		"react-router-dom": "^6.10.0"
	},
	"devDependencies": {
		"@vitejs/plugin-react": "2.2.0",
		"eslint": "8.26.0",
		"eslint-config-prettier": "8.5.0",
		"eslint-config-standard": "17.0.0",
		"eslint-plugin-import": "2.26.0",
		"eslint-plugin-n": "15.3.0",
		"eslint-plugin-promise": "6.1.1",
		"eslint-plugin-react": "7.31.10",
		"eslint-plugin-react-hooks": "^4.6.0",
		"prettier": "2.7.1",
		"vite": "3.2.0"
	}

Any idea how to fix it?
Thank you so much

**Comment by Ariel-1979** [comment]
Extension of package.json

	"scripts": {
		"dev": "vite",
		"build": "vite build",
		"preview": "vite preview",
		"format": "prettier --write .",
		"lint": "eslint . --ext .js,.jsx --fix"
	},
	"dependencies": {
		"easyinvoice": "^3.0.12",
		"pdfjs": "^2.4.7",
		"react": "18.2.0",
		"react-dom": "18.2.0",
		"react-router-dom": "^6.10.0"
	},
	"devDependencies": {
		"@vitejs/plugin-react": "2.2.0",
		"eslint": "8.26.0",
		"eslint-config-prettier": "8.5.0",
		"eslint-config-standard": "17.0.0",
		"eslint-plugin-import": "2.26.0",
		"eslint-plugin-n": "15.3.0",
		"eslint-plugin-promise": "6.1.1",
		"eslint-plugin-react": "7.31.10",
		"eslint-plugin-react-hooks": "^4.6.0",
		"prettier": "2.7.1",
		"vite": "3.2.0"
	}

**Comment by dveldhoen** [comment]
Thanks for contacting us. We'll have a look and try to reproduce. Stay tuned!

**Comment by dveldhoen** [comment]
Hi, we found the issue and fixed it in version 3.0.15. Please update to the latest version and run build. That should work fine.

**Comment by Ariel-1979** [comment]
Hello. Indeed, now everything works perfectly.
Thank you very much for the support and for the quick attention.
At your entire disposal.
Greetings from Argentina, the land of Riquelme, Maradona and a certain Lionel MESSI.
Greetings, and thanks again.

**Comment by dveldhoen** [comment]
Glad to be of help. Thanks for the nice greetings. In my case, greetings from The Netherlands. Land of tulips, windmills and cheese. And off course some great soccer players.
