### ISSUE TITLE
Typescript Building TS2666

### ISSUE THREAD

**Issue by dlh2** [dveldhoen/easyinvoice#89]
node_modules/easyinvoice/src/lib/easyinvoice.d.ts:154:5 - error TS2666: Exports and export assignments are not permitted in module augmentations.

Showing part of compiler options:
```
"compilerOptions": {
      "target": "ES2020",
      "module": "ES2015",
      "moduleResolution": "node", // Node for ES6, Classic for Commonjs
      "lib": [
        "es2019",
        "dom"
      ],
      "strict": true,
      "esModuleInterop": true,
      "forceConsistentCasingInFileNames": true,
```

Error appeared when running: `tsc -p tsconfig.json`

**Comment by dveldhoen** [comment]
Thanks, we will look into it.

**Comment by dlh2** [comment]
I don't know what really happened but it seems to be a trouble in Typescript 5.0.4

I backported to 4.9.5 and it works, I haven't checked about 5.0.4. since I've checked that there's some incompatible stuff in my project with 5.0.4.

**Comment by dveldhoen** [comment]
Alright, thanks for letting us know. We will look into TS 5 compatibility as soon as we can.

**Comment by mtmfahathdev** [comment]
Hello @dveldhoen, I hope you're doing well. One of the major features was supposed to be launched last week, but it couldn't go live due to this issue. I would really appreciate it if you could fix this issue. Thank you.

**Comment by dveldhoen** [comment]
Hi, alright we will move up the priority on this one. I'll try to get back to you asap.

**Comment by dveldhoen** [comment]
We updated the package to 3.0.16. The issue should be fixed now. Can you verify please?

**Comment by dveldhoen** [comment]
I'm going to close this. I assume the problem has been fixed. Still would greatly appreciate it if you could let me know if this fixed your problem. Thank you in advance!

**Comment by mtmfahathdev** [comment]
Hi @dveldhoen  Thank you for your patience the issue got resolved. Thanks a lot
