### ISSUE TITLE
How can I contribute to this project

### ISSUE THREAD

**Issue by AlijiEmmanuel-dev** [dveldhoen/easyinvoice#9]
Please how can I contribute to this project, what are the guidelines I must follow.

**Comment by dveldhoen** [comment]
There are no guidelines established (yet), but we appreciate all help. Please add unit testing at least and send us a pull request. We will review it asap.

**Comment by dveldhoen** [comment]
We will come with some proper guidelines soon

**Comment by AlijiEmmanuel-dev** [comment]
Ok.
