### ISSUE TITLE
GDPR laws

### ISSUE THREAD

**Issue by dlh2** [dveldhoen/easyinvoice#91]
This is really important to notify in the NPM repository or the GitHub itself.

As some developers need the packages and with the current GDPR Europe Laws we can't make this into production without a signed agreement between the two companies.

_Originally posted by @dlh2 in https://github.com/dveldhoen/easyinvoice/issues/4#issuecomment-1527582299_

As commented in this issue, invoices usually include sensitive data as prior to the principles there must be a way that the user that uses the package knows that somehow this data is being sent into another place and then resent back for the purpose of the package.

**Comment by dveldhoen** [comment]
We will look into it, but since we are swamped with work and this is a free package we don't have the time at the moment. For now if this is a concern for you, best not use the package.
