### ISSUE TITLE
Support for clickable links

### ISSUE THREAD

**Issue by luphelelemsani** [dveldhoen/easyinvoice#92]
Are we able to embed clickable links on the invoice as text in the pdf? I tried to encode the html on the "bottom-notice" but when I decode it in the client side, it remains a base64 string.

**{
// other values...
 "bottom-notice": `Please click the link to make payment:${Buffer.from(`<a href='${transaction.authorizationUrl}' target='_blank'>${transaction.authorizationUrl}</a>`).toString('base64')}`      
      }**

**Comment by dveldhoen** [comment]
As our package is html based, you are able implement clickable links in the form of <a> tags. Here is a working sample:
'bottom-notice': '<a href="https://google.com">Click here to go to Google</a>',
