### ISSUE TITLE
Translation for VAT missing

### ISSUE THREAD

**Issue by Nubebuster** [dveldhoen/easyinvoice#94]
The translation for VAT is missing in the translate definition.
~~Also the default total is wrong. It is in Dutch "totaal" instead of in English~~

**Comment by Nubebuster** [comment]
There are a lot of things not working properly. The custom values in sender also don't work. 

I am using nodejs with typescript.

    "@types/node": "^18.15.11",
    "easyinvoice": "^3.0.19",

it was installed using "npm i easyinvoice"

Code:
`const kvk = "1111111";
  const btwNummer = "NL111.1111.11.B01";
  const asnBank = "11.11.11.11";
  const IBAN = "NL11ABNA111111111";
  const BIC = "ABNANL2A";
  const post = "Postbus 1";
  const zip = "1234 AZ";
  const city = "Amsterdam";
  const company = "John Doe Inc.";

  const date = new Date();
  const dueOffsetDays = 14;
  const due = new Date(date);
  due.setDate(due.getDate() + dueOffsetDays);

  const data: InvoiceData = {
    images: {
      // The logo on top of your invoice
      logo: readFileSync("pdfs/Logo.png", "base64"),
      // The invoice background
      //   background: "https://public.easyinvoice.cloud/img/watermark-draft.jpg",
    },
    // Your own data
    sender: {
      company: company,
      address: post,
      zip: zip,
      city: city,
      ASN: asnBank,
      IBAN: IBAN,
      BIC: BIC,
      //   country: "Samplecountry",
      //"custom1": "custom value 1",
      //"custom2": "custom value 2",
      //"custom3": "custom value 3"
    },
    // Your recipient
    client: {
      company: "Client Corp",
      address: "Clientstreet 456",
      zip: "4567 CD",
      city: "Clientcity",
      country: "Clientcountry",
      // "custom1": "custom value 1",
      // "custom2": "custom value 2",
      // "custom3": "custom value 3"
    },
    information: {
      // Invoice number
      number: "2021.0001",
      // Invoice data
      date: date.toLocaleDateString("NL-nl"),
      // Invoice due date
      "due-date": due.toLocaleDateString("NL-nl"),
    },
    // The products you would like to see on your invoice
    // Total values are being calculated automatically
    products: [
      {
        quantity: "1",
        description: "Factuur",
        "tax-rate": 21,
        price: 33.87,
      },
    ],
    // Settings to customize your invoice
    settings: {
      currency: "EUR", // See documentation 'Locales and Currency' for more info. Leave empty for no currency.
      locale: "nl-NL", // Defaults to en-US, used for number formatting (See documentation 'Locales and Currency')
      // "margin-top": 25, // Defaults to '25'
      // "margin-right": 25, // Defaults to '25'
      // "margin-left": 25, // Defaults to '25'
      // "margin-bottom": 25, // Defaults to '25'
      // "format": "A4", // Defaults to A4, options: A3, A4, A5, Legal, Letter, Tabloid
      // "height": "1000px", // allowed units: mm, cm, in, px
      // "width": "500px", // allowed units: mm, cm, in, px
      // "orientation": "landscape", // portrait or landscape, defaults to portrait
    },
    // Translate your invoice to your preferred language
    translate: {
      // "invoice": "FACTUUR",  // Default to 'INVOICE'
      // "number": "Nummer", // Defaults to 'Number'
      // "date": "Datum", // Default to 'Date'
      // "due-date": "Verloopdatum", // Defaults to 'Due Date'
      // "subtotal": "Subtotaal", // Defaults to 'Subtotal'
      // "products": "Producten", // Defaults to 'Products'
      // "quantity": "Aantal", // Default to 'Quantity'
      // "price": "Prijs", // Defaults to 'Price'
      // "product-total": "Totaal", // Defaults to 'Total'
      //   total: "Total", // Defaults to 'Total'
      //   vat: "BTW", // Defaults to 'vat'
    },
    "bottom-notice": 'Wij verzoeken u vriendelijk betaling binnen ${dueOffsetDays} dagen na factuurdatum op rekeningnummer ${IBAN} o.v.v. het factuurnummer.',
  };
  const invoice = await easyinvoice.createInvoice(data);

  writeFileSync("pdfs/test.pdf", invoice.pdf, "base64");`

Result:


[test.pdf](https://github.com/dveldhoen/easyinvoice/files/11617656/test.pdf)

**Comment by Nubebuster** [comment]
Here is the translations from easyinvoice.d.ts

`    export interface InvoiceTranslations {
        invoice?: string;
        number?: string;
        date?: string;
        "due-date"?: string;
        subtotal?: string;
        products?: string;
        quantity?: string;
        price?: string;
        "product-total"?: string;
        total?: string;
    }
`

**Comment by dveldhoen** [comment]
For the custom values you are using the wrong keys. You should use:
custom1: 'ASN: ' + asnBank
custom2: 'IBAN: ' + IBAN
For example, it's important to keep the keys custom1, 2 and 3.

With regards to the type definitions vat is missing indeed, still you can use it if you ignore the type definition. You can try it in our JSFiddle from the Readme.

**Comment by Nubebuster** [comment]
Okay that makes sense. Unfortunately without the type definition it won't compile :/ Is it possible that the type definition is updated?

**Comment by dveldhoen** [comment]
I'm fixing it as we speak. Shouldn't take more than a few minutes.

**Comment by dveldhoen** [comment]
Version 3.0.20 just got published. Can you try if that fixes things for you?
