### ISSUE TITLE
Customize template working different than documentation

### ISSUE THREAD

**Issue by Nubebuster** [dveldhoen/easyinvoice#95]
I am trying to customize the template but there are some problems.

The template property wants a () => Buffer and not a Buffer

This does not print test. So it must be a type mistake
```
    customize: {
      template: () => {
        console.log("test");
        return readFileSync("pdfs/invoice.html");
      },
    },
```
    
 Also in typescript the readFileSync("invoice.html", "base64") is ambiguous and can return both a string and a Buffer. I don't know how to specify which should be used. Only by writing readFileSync("pdfs/invoice.html") without base64
 fs.d.ts:
 ```
     export function readFileSync(
        path: PathOrFileDescriptor,
        options?: {
            encoding?: null | undefined;
            flag?: string | undefined;
        } | null
    ): Buffer;

    export function readFileSync(
        path: PathOrFileDescriptor,
        options:
            | {
                  encoding: BufferEncoding;
                  flag?: string | undefined;
              }
            | BufferEncoding
    ): string;
```

**Comment by dveldhoen** [comment]
Note that console.log in the template property won't work. It should be base64 encoded html.

**Comment by dveldhoen** [comment]
The update is pushed and should be available shortly. 3.0.21 should expect a string for template.

**Comment by dveldhoen** [comment]
Feel free to create a pull request if you encounter anything else.
