### ISSUE TITLE
Custom fields not working

### ISSUE THREAD

**Issue by LouisMuriuki** [dveldhoen/easyinvoice#98]
Hi,
Am trying to add custom information about the seller and client as in the follwing:
`sender: {
        company: fromdata.name,
        address: fromdata.address,
        phone: fromdata.phone,
        email: fromdata.email,
        city: fromdata.city,
        website: fromdata.website
        ,`
Is this the right way to add the custom fields because they don't show up on the actual invoice

**Comment by dveldhoen** [comment]
You have to use the actual "custom1": website as key.

**Comment by LouisMuriuki** [comment]
Okay👍. Also is there away we can a custom invoice message to the receiver, in such a format
![image](https://github.com/dveldhoen/easyinvoice/assets/42152260/27d0d010-ecb6-434b-9ae5-8b4c73b6e61a)

**Comment by dveldhoen** [comment]
Yes, bottomNotice key. Please read the docs.
